// Characters page
export const FETCH_CHARACTERS = 'FETCH_CHARACTERS';
export const PENDING_CHARACTERS = 'PENDING_CHARACTERS';
export const REJECT_CHARACTERS = 'REJECT_CHARACTERS';

// CharacterDetails page
export const FETCH_SINGLECHARACTER = 'FETCH_SINGLECHARACTER';
export const PENDING_SINGLECHARACTER = 'PENDING_SINGLECHARACTER';
export const REJECT_SINGLECHARACTER = 'REJECT_SINGLECHARACTER';

// reset data
export const RESET_DATA = 'RESET_DATA';

// Change Page Parameter
export const CHANGE_PARAMS = 'CHANGE_PARAMS';
export const LOAD_MORE_DATA = 'LOAD_MORE_DATA';

// Search Page
export const SEARCH_CHARACTERS = 'SEARCH_CHARACTERS';
// export const CHANGE_PAGE_SEARCHPARAMS = 'CHANGE_PAGE_SEARCHPARAMS';
